# Generated by Django 2.2.5 on 2020-06-30 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_site', '0071_auto_20200624_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('clearance_level', models.IntegerField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quality', models.IntegerField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('face', models.ManyToManyField(blank=True, to='kuroko.face')),
                ('kdhi_db_figure', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main_site.individual')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='face',
            name='face',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kuroko.image'),
        ),
    ]
