# Generated by Django 2.2.5 on 2020-06-30 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuroko', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='face_to_figure_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='face',
            old_name='clearance_level',
            new_name='image_quality',
        ),
        migrations.RemoveField(
            model_name='face',
            name='face',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='face',
        ),
        migrations.AddField(
            model_name='face',
            name='image_filename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='image',
        ),
        migrations.AddField(
            model_name='face_to_figure_link',
            name='face',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kuroko.face'),
        ),
        migrations.AddField(
            model_name='face_to_figure_link',
            name='figure',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='kuroko.figure'),
        ),
        migrations.AddField(
            model_name='face',
            name='assc_figure',
            field=models.ManyToManyField(blank=True, through='kuroko.face_to_figure_link', to='kuroko.figure'),
        ),
    ]
