# Generated by Django 2.2.5 on 2020-06-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuroko', '0002_auto_20200629_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='image_filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='face',
            name='image_quality',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
