# Generated by Django 2.2.5 on 2020-06-30 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuroko', '0003_auto_20200629_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='verified_figure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_figure', to='kuroko.figure'),
        ),
    ]
