# Generated by Django 2.2.5 on 2020-06-30 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuroko', '0004_face_verified_figure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='kdhi_db_figure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_site.individual'),
        ),
    ]
