# Generated by Django 2.2.5 on 2020-06-30 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuroko', '0005_auto_20200630_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='verified_figure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='index_figure', to='kuroko.figure'),
        ),
        migrations.AlterField(
            model_name='face_to_figure_link',
            name='face',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuroko.face'),
        ),
        migrations.AlterField(
            model_name='face_to_figure_link',
            name='figure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuroko.figure'),
        ),
    ]
