# Generated by Django 3.0.4 on 2020-03-13 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_site', '0008_auto_20200311_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='overseas_tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_description', models.TextField(max_length=20000)),
                ('event_title', models.CharField(max_length=200)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_photo', models.URLField(blank=True)),
                ('event_photo_add_1', models.URLField(blank=True)),
                ('event_photo_add_2', models.URLField(blank=True)),
                ('event_photo_add_3', models.URLField(blank=True)),
                ('participant_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.individual')),
            ],
        ),
    ]
