# Generated by Django 2.2.5 on 2020-03-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0008_auto_20200311_0813'),
        ('trackers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overseas_tracker',
            name='participant_one',
        ),
        migrations.AddField(
            model_name='overseas_tracker',
            name='participant_one',
            field=models.ManyToManyField(to='main_site.individual'),
        ),
    ]
