# Generated by Django 2.2.5 on 2020-03-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0009_auto_20200313_1729'),
        ('trackers', '0002_auto_20200313_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overseas_tracker',
            old_name='participant_one',
            new_name='participant_DPRK',
        ),
        migrations.CreateModel(
            name='inter_kroean_tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_description', models.TextField(max_length=20000)),
                ('event_title', models.CharField(max_length=200)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_photo', models.URLField(blank=True)),
                ('event_photo_add_1', models.URLField(blank=True)),
                ('event_photo_add_2', models.URLField(blank=True)),
                ('event_photo_add_3', models.URLField(blank=True)),
                ('participant_ROK', models.ManyToManyField(to='main_site.rok_individual')),
            ],
        ),
    ]
