# Generated by Django 2.2.5 on 2020-03-13 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0009_auto_20200313_1729'),
        ('trackers', '0003_auto_20200313_1729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='inter_kroean_tracker',
            new_name='inter_korean_tracker',
        ),
    ]
