# Generated by Django 2.2.5 on 2020-03-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0009_auto_20200313_1729'),
        ('trackers', '0004_auto_20200313_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='inter_korean_tracker',
            name='participant_DPRK',
            field=models.ManyToManyField(to='main_site.individual'),
        ),
    ]
