# Generated by Django 2.2.5 on 2020-03-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0005_inter_korean_tracker_participant_dprk'),
    ]

    operations = [
        migrations.AddField(
            model_name='inter_korean_tracker',
            name='country_choices',
            field=models.CharField(default='N/A', max_length=200),
            preserve_default=False,
        ),
    ]
