# Generated by Django 2.2.5 on 2020-03-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0006_inter_korean_tracker_country_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inter_korean_tracker',
            old_name='event_description',
            new_name='MOU_description',
        ),
        migrations.RenameField(
            model_name='inter_korean_tracker',
            old_name='country_choices',
            new_name='event_location',
        ),
        migrations.AddField(
            model_name='inter_korean_tracker',
            name='document_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='inter_korean_tracker',
            name='event_venue',
            field=models.CharField(default='Unspecified', max_length=200),
            preserve_default=False,
        ),
    ]
