# Generated by Django 2.2.5 on 2020-03-30 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0023_glossary_item'),
        ('trackers', '0009_overseas_tracker_event_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='inter_korean_tracker',
            name='DPRK_head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dprk_head', to='main_site.individual'),
        ),
        migrations.AddField(
            model_name='inter_korean_tracker',
            name='ROK_head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rok_head', to='main_site.rok_individual'),
        ),
        migrations.AlterField(
            model_name='inter_korean_tracker',
            name='participant_DPRK',
            field=models.ManyToManyField(related_name='dprk_delegation', to='main_site.individual'),
        ),
        migrations.AlterField(
            model_name='inter_korean_tracker',
            name='participant_ROK',
            field=models.ManyToManyField(related_name='rok_delegation', to='main_site.rok_individual'),
        ),
    ]
