# Generated by Django 2.2.5 on 2020-03-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0010_auto_20200330_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inter_korean_tracker',
            name='participant_DPRK',
            field=models.ManyToManyField(null=True, related_name='dprk_delegation', to='main_site.individual'),
        ),
        migrations.AlterField(
            model_name='inter_korean_tracker',
            name='participant_ROK',
            field=models.ManyToManyField(null=True, related_name='rok_delegation', to='main_site.rok_individual'),
        ),
    ]
