# Generated by Django 2.2.5 on 2020-03-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0012_auto_20200330_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='country_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
