# Generated by Django 2.2.5 on 2020-03-30 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0014_auto_20200330_0649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='overseas_topics',
            new_name='overseas_topic',
        ),
    ]
