# Generated by Django 2.2.5 on 2020-04-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0015_auto_20200330_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inter_korean_tracker',
            name='participant_DPRK',
            field=models.ManyToManyField(blank=True, related_name='dprk_delegation', to='main_site.individual'),
        ),
        migrations.AlterField(
            model_name='inter_korean_tracker',
            name='participant_ROK',
            field=models.ManyToManyField(blank=True, default='Kim Jong Un', related_name='rok_delegation', to='main_site.rok_individual'),
        ),
    ]
