# Generated by Django 2.2.5 on 2020-05-13 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0016_auto_20200401_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inter_korean_tracker',
            old_name='event_title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='overseas_tracker',
            old_name='event_title',
            new_name='name',
        ),
    ]
