# Generated by Django 2.2.5 on 2020-05-15 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0050_auto_20200512_1837'),
        ('trackers', '0017_auto_20200512_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='overseas_tracker',
            name='DPRK_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dprk_overseas_head', to='main_site.individual'),
        ),
    ]
