# Generated by Django 2.2.5 on 2020-05-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0018_overseas_tracker_dprk_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='overseas_tracker',
            name='event_coverage',
            field=models.URLField(blank=True),
        ),
    ]
