# Generated by Django 2.2.5 on 2020-05-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0020_overseas_tracker_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inter_korean_tracker',
            options={'ordering': ('event_date', 'name')},
        ),
        migrations.AlterModelOptions(
            name='overseas_tracker',
            options={'ordering': ('event_date', 'name')},
        ),
    ]
