# Generated by Django 2.2.5 on 2020-05-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0021_auto_20200515_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='overseas_tracker',
            name='event_return',
            field=models.DateField(blank=True, null=True),
        ),
    ]
