# Generated by Django 2.2.5 on 2020-05-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0022_overseas_tracker_event_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overseas_tracker',
            name='participant_DPRK',
            field=models.ManyToManyField(null=True, to='main_site.individual'),
        ),
    ]
