# Generated by Django 2.2.5 on 2020-05-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0024_auto_20200515_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='inter_korean_tracker',
            name='slug',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='inter_korean_tracker',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='overseas_tracker',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='overseas_tracker',
            name='slug',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
