# Generated by Django 2.2.5 on 2020-05-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0025_auto_20200515_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='inter_korean_tracker',
            name='meeting_topics',
            field=models.ManyToManyField(blank=True, null=True, to='trackers.overseas_topic'),
        ),
        migrations.RemoveField(
            model_name='overseas_tracker',
            name='country_choices',
        ),
        migrations.AddField(
            model_name='overseas_tracker',
            name='country_choices',
            field=models.ManyToManyField(blank=True, null=True, to='trackers.country_list'),
        ),
        migrations.RemoveField(
            model_name='overseas_tracker',
            name='overseas_topics',
        ),
        migrations.AddField(
            model_name='overseas_tracker',
            name='overseas_topics',
            field=models.ManyToManyField(blank=True, null=True, to='trackers.overseas_topic'),
        ),
    ]
