# Generated by Django 2.2.5 on 2020-06-01 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0027_auto_20200526_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overseas_tracker',
            options={'ordering': ('-event_date', 'name')},
        ),
    ]
