# Generated by Django 2.2.5 on 2020-06-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0029_overseas_tracker_event_photo_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='inter_korean_tracker',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='overseas_tracker',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
