# Generated by Django 2.2.5 on 2020-06-26 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0031_inter_korean_tracker_event_photo_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='inter_korean_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='inter_korean_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='inter_korean_subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='inter_korean_tracker',
            name='document_name',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inter_korean_tracker',
            name='event_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inter_korean_tracker',
            name='participant_ROK',
            field=models.ManyToManyField(blank=True, related_name='rok_delegation', to='main_site.rok_individual'),
        ),
        migrations.AddField(
            model_name='inter_korean_tracker',
            name='event_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_category', to='trackers.inter_korean_category'),
        ),
        migrations.AddField(
            model_name='inter_korean_tracker',
            name='event_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_level', to='trackers.inter_korean_level'),
        ),
        migrations.AddField(
            model_name='inter_korean_tracker',
            name='event_subcategory',
            field=models.ManyToManyField(blank=True, related_name='event_subcategory', to='trackers.inter_korean_subcategory'),
        ),
    ]
