# Generated by Django 2.2.5 on 2020-06-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0035_auto_20200626_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inter_korean_tracker',
            name='document_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='inter_korean_tracker',
            name='event_photo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='inter_korean_tracker',
            name='event_photo_add_1',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='inter_korean_tracker',
            name='event_photo_add_2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='inter_korean_tracker',
            name='event_photo_add_3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='inter_korean_tracker',
            name='media_coverage',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
