# Generated by Django 2.2.5 on 2020-06-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0036_auto_20200626_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inter_korean_tracker',
            name='event_location',
        ),
    ]
