# Generated by Django 2.2.5 on 2020-06-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_archive', '0002_auto_20200617_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state_media_article',
            name='language',
            field=models.CharField(default='ENG', max_length=10),
        ),
    ]
