# Generated by Django 2.2.5 on 2020-06-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_archive', '0003_auto_20200617_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='uritv_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField()),
                ('date', models.DateField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('title_translated', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('category_translated', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('description_translated', models.CharField(max_length=200)),
                ('korean_keyword', models.CharField(max_length=200)),
                ('korean_keyword_translated', models.CharField(max_length=200)),
                ('english_keyword', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('-date', 'title_translated'),
            },
        ),
    ]
