# Generated by Django 2.2.5 on 2020-06-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_archive', '0004_uritv_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uritv_video',
            name='source',
        ),
        migrations.AddField(
            model_name='uritv_video',
            name='file_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='uritv_video',
            name='uri_source',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='uritv_video',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='uritv_video',
            name='category_translated',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='uritv_video',
            name='date',
            field=models.DateField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='uritv_video',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='uritv_video',
            name='description_translated',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='uritv_video',
            name='english_keyword',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='uritv_video',
            name='korean_keyword',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='uritv_video',
            name='korean_keyword_translated',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='uritv_video',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='uritv_video',
            name='title_translated',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
