# Generated by Django 2.2.5 on 2020-06-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_archive', '0007_auto_20200624_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='uritv_video',
            name='db_code',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
