# Generated by Django 2.2.5 on 2020-06-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_archive', '0008_uritv_video_db_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uritv_video',
            options={'ordering': ('db_code', '-date', 'title_translated')},
        ),
        migrations.AddField(
            model_name='uritv_video',
            name='s3_verified',
            field=models.BooleanField(default=False),
        ),
    ]
