# Generated by Django 2.2.5 on 2020-07-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_archive', '0009_auto_20200629_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state_media_article',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
