# Generated by Django 2.2.5 on 2020-06-17 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='country_list',
            new_name='subscriber',
        ),
    ]
