# Generated by Django 2.2.5 on 2020-03-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='individual',
        ),
        migrations.DeleteModel(
            name='institution',
        ),
        migrations.DeleteModel(
            name='position',
        ),
    ]
