# Generated by Django 2.2.5 on 2020-03-09 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_individual_institution_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='positions',
            field=models.ManyToManyField(blank=True, through='main_site.position', to='main_site.institution'),
        ),
        migrations.AddField(
            model_name='position',
            name='institution',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_site.institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_site.individual'),
            preserve_default=False,
        ),
    ]
