# Generated by Django 2.2.5 on 2020-03-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_auto_20200309_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='bio',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='individual',
            name='education',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='individual',
            name='full_resolution_photo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='hometown',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='individual',
            name='icon',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='photo_credit',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='individual',
            name='sources',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='individual',
            name='video_2_caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='individual',
            name='video_2_source',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='video_caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='individual',
            name='video_source',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='additional_information',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='institution',
            name='tag_one',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='institution',
            name='tag_three',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='institution',
            name='tag_two',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
