# Generated by Django 2.2.5 on 2020-03-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_auto_20200309_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='confirmation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='confirmation_src',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='position',
            name='replaced',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
