# Generated by Django 2.2.5 on 2020-03-09 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_auto_20200309_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='positions',
        ),
    ]
