# Generated by Django 2.2.5 on 2020-03-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0007_remove_individual_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='bio',
            field=models.TextField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='individual',
            name='sources',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='institution',
            name='additional_information',
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AlterField(
            model_name='institution',
            name='function',
            field=models.TextField(max_length=20000),
        ),
    ]
