# Generated by Django 2.2.5 on 2020-03-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0010_rok_institution_rok_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='rok_institution',
            name='history',
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AlterField(
            model_name='rok_institution',
            name='function',
            field=models.TextField(blank=True, max_length=20000),
        ),
    ]
