# Generated by Django 2.2.5 on 2020-03-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0011_auto_20200313_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rok_individual',
            old_name='education',
            new_name='education_itmes',
        ),
        migrations.AddField(
            model_name='rok_individual',
            name='awards_items',
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name='rok_individual',
            name='awards_timeline',
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name='rok_individual',
            name='career_items',
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name='rok_individual',
            name='career_timeline',
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name='rok_individual',
            name='education_timeline',
            field=models.TextField(blank=True, max_length=20000),
        ),
    ]
