# Generated by Django 2.2.5 on 2020-03-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0012_auto_20200313_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rok_individual',
            name='education_itmes',
        ),
        migrations.AddField(
            model_name='rok_individual',
            name='education_items',
            field=models.TextField(blank=True, max_length=20000),
        ),
    ]
