# Generated by Django 2.2.5 on 2020-03-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0014_remove_rok_individual_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rok_individual',
            name='name_korean',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
