# Generated by Django 2.2.5 on 2020-03-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0015_auto_20200315_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='rok_individual',
            name='name_true',
            field=models.CharField(default='BLANK', max_length=200),
            preserve_default=False,
        ),
    ]
