# Generated by Django 2.2.5 on 2020-03-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0021_auto_20200323_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
