# Generated by Django 2.2.5 on 2020-04-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0023_glossary_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='bio',
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AlterField(
            model_name='individual',
            name='sources',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='institution',
            name='function',
            field=models.TextField(blank=True, max_length=20000),
        ),
    ]
