# Generated by Django 2.2.5 on 2020-04-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0025_auto_20200406_0811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('person', 'position_rank')},
        ),
        migrations.AddField(
            model_name='position',
            name='position_rank',
            field=models.IntegerField(default=0),
        ),
    ]
