# Generated by Django 2.2.5 on 2020-04-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0027_auto_20200406_0817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('-position_rank', 'person')},
        ),
    ]
