# Generated by Django 2.2.5 on 2020-04-06 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0028_auto_20200406_0818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('position_rank', 'person')},
        ),
    ]
