# Generated by Django 2.2.5 on 2020-04-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0029_auto_20200406_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='confirmation_date',
            field=models.DateField(blank=True, default='2019-04-12', null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='confirmation_src',
            field=models.CharField(default='First Session of 14th SPA Held', max_length=200),
        ),
    ]
