# Generated by Django 2.2.5 on 2020-04-13 23:28

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0030_auto_20200413_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='additional_figures',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='organization_structure',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='sources',
            field=models.TextField(blank=True, max_length=20000),
        ),
    ]
