# Generated by Django 2.2.5 on 2020-04-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0031_auto_20200413_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='sources',
            field=models.TextField(blank=True, default='[1] Ministry of Unification, "2019년 북한 기관별 인명록"  2018-12-27', max_length=20000),
        ),
    ]
