# Generated by Django 2.2.5 on 2020-04-13 23:33

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0032_auto_20200413_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='additional_information',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='function',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
    ]
