# Generated by Django 2.2.5 on 2020-04-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0033_auto_20200413_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='function_plain',
            field=models.TextField(blank=True, max_length=20000),
        ),
    ]
