# Generated by Django 2.2.5 on 2020-04-13 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0034_institution_function_plain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='function_plain',
        ),
    ]
