# Generated by Django 2.2.5 on 2020-04-14 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0037_auto_20200413_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='sources',
        ),
    ]
