# Generated by Django 2.2.5 on 2020-04-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0038_remove_institution_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='rok_institution',
            name='qs_slug',
            field=models.CharField(default='SLUG MISSING', max_length=250),
        ),
    ]
