# Generated by Django 2.2.5 on 2020-04-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0039_rok_institution_qs_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rok_institution',
            name='qs_slug',
            field=models.TextField(default='SLUG MISSING', max_length=250),
        ),
    ]
