# Generated by Django 2.2.5 on 2020-04-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0040_auto_20200430_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='rok_position',
            name='position_rank',
            field=models.IntegerField(default=0),
        ),
    ]
