# Generated by Django 2.2.5 on 2020-04-30 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0041_rok_position_position_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rok_individual',
            old_name='name_true',
            new_name='name_slug',
        ),
    ]
