# Generated by Django 2.2.5 on 2020-04-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0043_auto_20200430_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='rok_institution',
            name='official_webpage',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
