# Generated by Django 2.2.5 on 2020-04-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0044_rok_institution_official_webpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rok_institution',
            name='sources_add',
            field=models.TextField(blank=True, max_length=20000),
        ),
    ]
