# Generated by Django 2.2.5 on 2020-04-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0045_rok_institution_sources_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rok_institution',
            name='additional_information',
        ),
    ]
