# Generated by Django 2.2.5 on 2020-05-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0047_auto_20200501_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='full_resolution_photo',
            field=models.URLField(default='1_Outline_Blank'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='icon',
            field=models.URLField(default='1_Outline_Blank'),
        ),
    ]
