# Generated by Django 2.2.5 on 2020-05-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0048_auto_20200501_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='tag_three',
            new_name='sector_tag_1',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='tag_two',
            new_name='sphere_tag',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='tag_one',
            new_name='tripartite_tag',
        ),
        migrations.AddField(
            model_name='institution',
            name='sector_tag_2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
