# Generated by Django 2.2.5 on 2020-05-12 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0049_auto_20200505_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='glossary_item',
            old_name='title',
            new_name='name',
        ),
    ]
