# Generated by Django 2.2.5 on 2020-05-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0050_auto_20200512_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='replaced',
            field=models.BooleanField(null=True),
        ),
    ]
