# Generated by Django 2.2.5 on 2020-05-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0051_auto_20200515_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='replaced',
            field=models.BooleanField(default=False),
        ),
    ]
