# Generated by Django 2.2.5 on 2020-05-15 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0052_auto_20200515_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='full_resolution_photo',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='icon',
        ),
    ]
