# Generated by Django 2.2.5 on 2020-05-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0056_auto_20200527_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='replaced',
        ),
        migrations.AddField(
            model_name='position',
            name='position_status',
            field=models.CharField(choices=[('Active', 'AC'), ('Potentially Removed', 'UN'), ('Removed', 'RE')], default='Active', max_length=2),
        ),
    ]
