# Generated by Django 2.2.5 on 2020-05-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0057_auto_20200527_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_status',
            field=models.CharField(choices=[('AC', 'Active'), ('UN', 'Potentially Removed'), ('RE', 'Removed')], default='AC', max_length=2),
        ),
    ]
