# Generated by Django 2.2.5 on 2020-05-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0058_auto_20200527_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Unclear', 'Unclear'), ('Removed', 'Removed')], default='Active', max_length=20),
        ),
    ]
