# Generated by Django 2.2.5 on 2020-05-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0059_auto_20200527_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='confirmation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='confirmation_src',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
