# Generated by Django 2.2.5 on 2020-06-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0060_auto_20200527_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='confirmation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
