# Generated by Django 2.2.5 on 2020-06-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0063_auto_20200601_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Unclear', 'Unclear'), ('Removed', 'Removed'), ('Likely', 'Likely')], default='Active', max_length=20),
        ),
    ]
