# Generated by Django 2.2.5 on 2020-06-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0064_auto_20200604_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Likely', 'Likely'), ('Unclear', 'Unclear'), ('Removed', 'Removed')], default='Active', max_length=20),
        ),
    ]
