# Generated by Django 2.2.5 on 2020-06-17 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0065_auto_20200613_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossary_item',
            options={'ordering': ('name',)},
        ),
    ]
