# Generated by Django 2.2.5 on 2020-06-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0068_auto_20200622_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='dprk_institution_tag',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
