# Generated by Django 2.2.5 on 2020-06-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0070_auto_20200622_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='function_tags',
            field=models.ManyToManyField(blank=True, to='main_site.dprk_institution_tag'),
        ),
    ]
