# Generated by Django 2.2.5 on 2020-03-08 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_archive', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='article',
            new_name='article_model',
        ),
    ]
