# Generated by Django 2.2.5 on 2020-03-17 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='document_collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=20000)),
                ('creator', models.CharField(max_length=200)),
                ('document_text', models.TextField(blank=True, max_length=20000)),
                ('url_substring', models.CharField(max_length=200)),
                ('country_of_origin', models.CharField(max_length=200)),
                ('document_source', models.CharField(max_length=200)),
                ('rights', models.CharField(max_length=2000)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document_collection')),
            ],
        ),
    ]
