# Generated by Django 2.2.5 on 2020-03-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateField(blank=True, default='2020-01-01'),
            preserve_default=False,
        ),
    ]
