# Generated by Django 2.2.5 on 2020-04-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_collection',
            name='directory',
            field=models.CharField(default='Kim Jong Un', max_length=200),
            preserve_default=False,
        ),
    ]
