# Generated by Django 2.2.5 on 2020-04-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_collection_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='rights',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='document',
            name='url_substring',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
