# Generated by Django 2.2.5 on 2020-04-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20200402_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='index_outdated',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='url_substring',
            field=models.CharField(blank=True, default='https://kdhi-resources.s3.amazonaws.com/kdhi.org/Assets/Documents/Democratization/1986/', max_length=200),
        ),
    ]
