# Generated by Django 2.2.5 on 2020-04-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20200402_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='document_collection',
            options={'ordering': ('name',)},
        ),
    ]
