# Generated by Django 2.2.5 on 2020-04-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20200409_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url_substring',
            field=models.CharField(blank=True, default='https://kdhi-resources.s3.amazonaws.com/kdhi.org/Assets/Documents/', max_length=200),
        ),
    ]
