# Generated by Django 2.2.5 on 2020-04-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_collection_timeline_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_13',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
