# Generated by Django 2.2.5 on 2020-04-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_auto_20200420_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection_timeline_item',
            name='section_title',
            field=models.CharField(default='NO TITLE', max_length=500),
            preserve_default=False,
        ),
    ]
