# Generated by Django 2.2.5 on 2020-04-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_auto_20200420_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_10_content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_11_content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_12_content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_13_content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_1_content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_2_content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_3_content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_4_content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_5_content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_6_content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_7_content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_8_content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='day_9_content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
