# Generated by Django 2.2.5 on 2020-04-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_auto_20200426_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='month_int',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='collection_timeline_item',
            name='year',
            field=models.IntegerField(),
        ),
    ]
