# Generated by Django 2.2.5 on 2020-05-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_auto_20200426_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_collection',
            name='hero',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
