# Generated by Django 2.2.5 on 2020-05-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_document_collection_hero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document_collection',
            options={'ordering': ('weight', 'name')},
        ),
        migrations.AddField(
            model_name='document_collection',
            name='weight',
            field=models.IntegerField(blank=True, default=10),
            preserve_default=False,
        ),
    ]
