# Generated by Django 2.2.5 on 2020-05-03 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_auto_20200503_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection_timeline_item',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document_collection'),
        ),
    ]
