# Generated by Django 2.2.5 on 2020-05-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_collection_timeline_item_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection_timeline_item',
            name='collection',
        ),
    ]
