# Generated by Django 2.2.5 on 2020-05-03 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_auto_20200503_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='critical_oral_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=300)),
                ('pdf_location', models.CharField(blank=True, max_length=300)),
                ('ses_location', models.CharField(blank=True, max_length=300)),
                ('ses_date', models.DateField(blank=True)),
                ('ses_host', models.CharField(blank=True, max_length=300)),
                ('ses_desc', models.TextField(blank=True, max_length=1000)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document_collection')),
            ],
        ),
    ]
