# Generated by Django 2.2.5 on 2020-05-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_critical_oral_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_collection',
            name='bluff',
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name='document_collection',
            name='doc_bluf',
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name='document_collection',
            name='oral_bluf',
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AddField(
            model_name='document_collection',
            name='timeline_bluf',
            field=models.TextField(blank=True, max_length=20000),
        ),
    ]
