# Generated by Django 2.2.5 on 2020-05-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_document_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=models.ManyToManyField(to='documents.document_keyword'),
        ),
    ]
