# Generated by Django 2.2.5 on 2020-06-15 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0027_auto_20200512_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_keyword',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document_collection'),
        ),
    ]
