# Generated by Django 2.2.5 on 2020-06-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_document_keyword_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url_substring',
            field=models.CharField(blank=True, default='https://kdhi-resources.s3.amazonaws.com/kdhi.org/Assets/Documents/1980+Gwangju+Massacre/', max_length=200),
        ),
    ]
