# Generated by Django 3.0.4 on 2020-05-17 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='face_instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuroko_id', models.CharField(max_length=200)),
                ('src_image', models.CharField(max_length=200)),
                ('image_quality', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='individual_instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('assc_face', models.ManyToManyField(related_name='individual_face', to='face_index.face_instance')),
            ],
        ),
        migrations.AddField(
            model_name='face_instance',
            name='individual_match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='face_index.individual_instance'),
        ),
    ]
